version: 2.1
jobs:
  test:
      executor:
        name: node/default
        tag: '13'
      steps:
        - checkout
        - node/install-packages
        - run:
            command: npm run test
  eslint:
      docker:
        - image: circleci/node:12.18.3
      executor: default
      steps:
        - attach_workspace:
            at: ~/
        - eslint
        - store_test_results:
            path: reports/eslint
        - store_artifacts:
            path: reports/eslint
  build:
    docker:
      - image: circleci/node:12.18.3
    executor: default
    steps:
      - checkout
      - run:
          command: npm run build


orbs:
  node: circleci/node@3.0.0
workflows:
  tests:
    jobs:
      - test
      - build
      - eslint

