version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run: npm build

  eslint:
      docker:
        - image: circleci/node:12.18.3
      executor: default
      steps:
        - attach_workspace:
            at: ~/
        - eslint
        - store_test_results:
            path: reports/eslint
        - store_artifacts:
            path: reports/eslint


orbs:
  node: circleci/node@3.0.0
workflows:
  tests:
    jobs:
      - test
      - eslint

